<?php

use App\Http\Controllers\AdminContentController;
use App\Http\Controllers\ApplicationLogController;
use App\Http\Controllers\AppearanceScheduleController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BroadcastController;
use App\Http\Controllers\CommitteeRegistrationController;
use App\Http\Controllers\CompetitionLocationController;
use App\Http\Controllers\DocumentSettingsController;
use App\Http\Controllers\JuknisSettingsController;
use App\Http\Controllers\OfficialRegistrationController;
use App\Http\Controllers\MfqScoringController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\ParticipantRegistrationController;
use App\Http\Controllers\ParticipantResultController;
use App\Http\Controllers\ScoringController;
use Illuminate\Support\Facades\Route;

Route::get('/', [PageController::class, 'home'])->name('home');
Route::get('/big-screen', [PageController::class, 'bigScreen'])->name('big-screen');
Route::get('/api/big-screen/current-participant', [PageController::class, 'apiCurrentParticipant'])->name('api.big-screen.current-participant');
Route::post('/api/big-screen/set-participant', [PageController::class, 'setCurrentParticipant'])->name('api.big-screen.set-participant');
Route::get('/jadwal/berlangsung', [PageController::class, 'ongoingSchedules'])->name('schedules.ongoing');
Route::redirect('/panduan/pendaftaran-official', '/panduan/pendaftaran-peserta');
Route::get('/panduan/pendaftaran-peserta', [PageController::class, 'participantRegistrationGuidePdf'])->name('participants.guide.pdf');
Route::get('/panduan/pendaftaran-peserta/snapshot', [PageController::class, 'participantRegistrationGuideSnapshot'])->name('participants.guide.snapshot');

Route::middleware('guest')->group(function (): void {
    Route::get('/login', [AuthController::class, 'create'])->name('login');
    Route::post('/login', [AuthController::class, 'store'])->name('login.store');
    Route::post('/lupa-password', [AuthController::class, 'requestPasswordReset'])
        ->middleware('throttle:5,1')
        ->name('password.reset.request');
});

Route::middleware(['auth', 'password.change'])->group(function (): void {
    Route::get('/dashboard', [PageController::class, 'dashboard'])->name('dashboard');
    Route::post('/dashboard/sinkronisasi-user', [PageController::class, 'syncDashboardUser'])->name('dashboard.user-sync');
    Route::post('/dashboard/password', [PageController::class, 'updateDashboardPassword'])->name('dashboard.password.update');
    Route::get('/dashboard/realtime-summary', [PageController::class, 'dashboardRealtimeSummary'])->name('dashboard.realtime-summary');
    Route::get('/leaderboard', [PageController::class, 'leaderboard'])->name('leaderboard.index');
    Route::get('/admin/log-aplikasi', [ApplicationLogController::class, 'index'])->middleware('role:admin,panitia')->name('application.logs');
    Route::get('/admin/official-kecamatan', [OfficialRegistrationController::class, 'index'])->middleware('role:admin')->name('officials.index');
    Route::post('/admin/official-kecamatan/preview', [OfficialRegistrationController::class, 'preview'])->middleware('role:admin')->name('officials.preview');
    Route::post('/admin/official-kecamatan', [OfficialRegistrationController::class, 'store'])->middleware('role:admin')->name('officials.store');
    Route::post('/admin/official-kecamatan/{official}/hapus', [OfficialRegistrationController::class, 'destroy'])->middleware('role:admin')->name('officials.destroy');
    Route::get('/admin/panitia-cabang', [CommitteeRegistrationController::class, 'index'])->middleware('role:admin')->name('committees.index');
    Route::post('/admin/panitia-cabang/preview', [CommitteeRegistrationController::class, 'preview'])->middleware('role:admin')->name('committees.preview');
    Route::post('/admin/panitia-cabang', [CommitteeRegistrationController::class, 'store'])->middleware('role:admin')->name('committees.store');
    Route::post('/admin/panitia-cabang/{committee}/akses-cabang', [CommitteeRegistrationController::class, 'updateBranches'])->middleware('role:admin')->name('committees.branches.update');
    Route::post('/admin/panitia-cabang/{committee}/hapus', [CommitteeRegistrationController::class, 'destroy'])->middleware('role:admin')->name('committees.destroy');
    Route::get('/admin/konten', [AdminContentController::class, 'index'])->middleware('role:admin,panitia')->name('admin.content');
    Route::post('/admin/konten/akses-official', [AdminContentController::class, 'updateOfficialAccess'])->middleware('role:admin')->name('admin.content.official-access.update');
    Route::post('/admin/konten/akses-maqra', [AdminContentController::class, 'updateMaqraAccess'])->middleware('role:admin')->name('admin.content.maqra-access.update');
    // Maqra Rounds CRUD
    Route::post('/admin/konten/maqra-round', [AdminContentController::class, 'storeMaqraRound'])->middleware('role:admin')->name('admin.content.maqra-rounds.store');
    Route::post('/admin/konten/maqra-round/{maqraRound}/edit', [AdminContentController::class, 'updateMaqraRound'])->middleware('role:admin')->name('admin.content.maqra-rounds.update');
    Route::post('/admin/konten/maqra-round/{maqraRound}/hapus', [AdminContentController::class, 'destroyMaqraRound'])->middleware('role:admin')->name('admin.content.maqra-rounds.destroy');
    // Maqra Schedules CRUD
    Route::post('/admin/konten/maqra-schedule', [AdminContentController::class, 'storeMaqraSchedule'])->middleware('role:admin')->name('admin.content.maqra-schedules.store');
    Route::post('/admin/konten/maqra-schedule/{maqraSchedule}/edit', [AdminContentController::class, 'updateMaqraSchedule'])->middleware('role:admin')->name('admin.content.maqra-schedules.update');
    Route::post('/admin/konten/maqra-schedule/{maqraSchedule}/hapus', [AdminContentController::class, 'destroyMaqraSchedule'])->middleware('role:admin')->name('admin.content.maqra-schedules.destroy');
    Route::post('/admin/konten/maqra-schedule/{maqraSchedule}/toggle', [AdminContentController::class, 'toggleMaqraSchedule'])->middleware('role:admin')->name('admin.content.maqra-schedules.toggle');
    Route::post('/admin/konten/sinkronisasi-kecamatan', [AdminContentController::class, 'syncDistricts'])->middleware('role:admin')->name('admin.content.districts.sync');
    Route::get('/admin/konten/projector-installer.ps1', [AdminContentController::class, 'projectorInstaller'])->middleware('role:admin,panitia')->name('admin.content.projector-installer');
    Route::post('/admin/konten/pengumuman', [AdminContentController::class, 'storeAnnouncement'])->middleware('role:admin,panitia')->name('admin.content.announcements.store');
    Route::post('/admin/konten/pengumuman/{announcement}/hapus', [AdminContentController::class, 'destroyAnnouncement'])->middleware('role:admin,panitia')->name('admin.content.announcements.destroy');
    Route::post('/admin/konten/jadwal', [AdminContentController::class, 'storeSchedule'])->middleware('role:admin,panitia')->name('admin.content.schedules.store');
    Route::post('/admin/konten/jadwal/{schedule}/status', [AdminContentController::class, 'updateScheduleStatus'])->middleware('role:admin,panitia')->name('admin.content.schedules.status');
    Route::post('/admin/konten/jadwal/{schedule}/hapus', [AdminContentController::class, 'destroySchedule'])->middleware('role:admin,panitia')->name('admin.content.schedules.destroy');
    Route::get('/admin/dokumen', [DocumentSettingsController::class, 'index'])->middleware('role:admin,panitia')->name('admin.documents');
    Route::post('/admin/dokumen', [DocumentSettingsController::class, 'update'])->middleware('role:admin,panitia')->name('admin.documents.update');
    Route::get('/admin/juknis', [JuknisSettingsController::class, 'index'])->middleware('role:admin')->name('admin.juknis');
    Route::post('/admin/juknis', [JuknisSettingsController::class, 'update'])->middleware('role:admin')->name('admin.juknis.update');
    Route::get('/admin/lokasi-mtq', [CompetitionLocationController::class, 'index'])->middleware('role:admin')->name('locations.index');
    Route::post('/admin/lokasi-mtq', [CompetitionLocationController::class, 'store'])->middleware('role:admin')->name('locations.store');
    Route::post('/admin/lokasi-mtq/sinkronisasi', [CompetitionLocationController::class, 'syncFromJson'])->middleware('role:admin')->name('locations.sync');
    Route::post('/admin/lokasi-mtq/{competitionLocation}', [CompetitionLocationController::class, 'update'])->middleware('role:admin')->name('locations.update');
    Route::post('/admin/lokasi-mtq/{competitionLocation}/foto-hapus', [CompetitionLocationController::class, 'destroyPhoto'])->middleware('role:admin')->name('locations.photo.destroy');
    Route::post('/admin/lokasi-mtq/{competitionLocation}/hapus', [CompetitionLocationController::class, 'destroy'])->middleware('role:admin')->name('locations.destroy');
    Route::get('/admin/galeri-mtq', [PageController::class, 'galleryDocumentation'])->middleware('role:admin,panitia,official,pendamping')->name('gallery.index');
    Route::post('/admin/galeri-mtq', [PageController::class, 'storeGalleryDocumentation'])->middleware('role:admin,panitia,official,pendamping')->name('gallery.store');
    Route::post('/admin/galeri-mtq/backfill-thumbnail', [PageController::class, 'backfillGalleryThumbnails'])->middleware('role:admin,panitia')->name('gallery.backfill');
    Route::post('/admin/galeri-mtq/{activityDocumentation}/cover-utama', [PageController::class, 'setGalleryMainCover'])->middleware('role:admin')->name('gallery.cover-main');
    Route::post('/admin/galeri-mtq/{activityDocumentation}/lepas-cover', [PageController::class, 'releaseGalleryMainCover'])->middleware('role:admin')->name('gallery.cover-release');
    Route::post('/admin/galeri-mtq/{activityDocumentation}/cover', [PageController::class, 'toggleGalleryCover'])->middleware('role:admin')->name('gallery.cover');
    Route::post('/admin/galeri-mtq/cover-bulk', [PageController::class, 'bulkSetGalleryCovers'])->middleware('role:admin')->name('gallery.cover-bulk');
    Route::post('/admin/galeri-mtq/{activityDocumentation}/urutan/{direction}', [PageController::class, 'moveGalleryCover'])->middleware('role:admin')->whereIn('direction', ['up', 'down'])->name('gallery.cover-move');
    Route::post('/admin/galeri-mtq/{activityDocumentation}/hapus', [PageController::class, 'destroyGalleryDocumentation'])->middleware('role:admin,panitia,official,pendamping')->name('gallery.destroy');
    Route::get('/juknis-mtq', [PageController::class, 'juknis'])->name('juknis.index');
    Route::get('/kategori-mtq', [PageController::class, 'categories'])->name('categories.index');
    Route::post('/kategori-mtq/{category}/nomor-lot', [PageController::class, 'updateCategoryLotSettings'])->middleware('role:admin')->name('categories.lot-settings.update');
    Route::get('/admin/maqra', [PageController::class, 'maqra'])->middleware('role:admin')->name('maqra.index');
    Route::get('/admin/maqra/template-csv', [PageController::class, 'maqraCsvTemplate'])->middleware('role:admin')->name('maqra.template-csv');
    Route::post('/admin/maqra', [PageController::class, 'storeMaqra'])->middleware('role:admin')->name('maqra.store');
    Route::post('/admin/maqra/preview', [PageController::class, 'previewMaqraCsv'])->middleware('role:admin')->name('maqra.preview');
    Route::post('/admin/maqra/laporan-csv', [PageController::class, 'downloadMaqraCsvReport'])->middleware('role:admin')->name('maqra.report');
    Route::post('/admin/maqra/import', [PageController::class, 'importMaqraCsv'])->middleware('role:admin')->name('maqra.import');
    Route::post('/admin/maqra/{maqraPackage}', [PageController::class, 'updateMaqra'])->middleware('role:admin')->name('maqra.update');
    Route::post('/admin/maqra/{maqraPackage}/hapus', [PageController::class, 'destroyMaqra'])->middleware('role:admin')->name('maqra.destroy');
    Route::get('/admin/lot-auto-calculate', [PageController::class, 'lotAutoCalculate'])->middleware('role:admin')->name('admin.lot-auto-calculate');
    Route::get('/admin/lot-auto-calculate/preview', [PageController::class, 'previewLotAutoCalculate'])->middleware('role:admin')->name('admin.lot-auto-calculate.preview');
    Route::get('/admin/penampilan', [AppearanceScheduleController::class, 'index'])->middleware('role:admin')->name('appearance.schedules');
    Route::post('/admin/penampilan', [AppearanceScheduleController::class, 'store'])->middleware('role:admin')->name('appearance.schedules.store');
    Route::delete('/admin/penampilan/{schedule}', [AppearanceScheduleController::class, 'destroy'])->middleware('role:admin')->name('appearance.schedules.destroy');
    Route::get('/admin/penampilan/hasil/{category}', [AppearanceScheduleController::class, 'results'])->middleware('role:admin')->name('appearance.results');
    Route::get('/admin/penampilan/hasil/{category}/pdf', [AppearanceScheduleController::class, 'exportPdf'])->middleware('role:admin')->name('appearance.results.pdf');
    Route::get('/admin/penampilan/export/pdf', [AppearanceScheduleController::class, 'exportAllPdf'])->middleware('role:admin')->name('appearance.export.all.pdf');
    Route::get('/admin/rangkaian-kegiatan/pdf', [AppearanceScheduleController::class, 'exportFullSchedulePdf'])->middleware('role:admin')->name('full.schedule.pdf');
    Route::get('/hasil-nilai', [ParticipantResultController::class, 'index'])->name('results.index');
    Route::get('/hasil-nilai/export', [ParticipantResultController::class, 'export'])->name('results.export');
    Route::get('/hasil-nilai/cetak', [ParticipantResultController::class, 'print'])->name('results.print');
    Route::get('/rekap-penilaian', [ParticipantResultController::class, 'recap'])->name('results.recap');
    Route::get('/rekap-penilaian/cetak', [ParticipantResultController::class, 'recapPrint'])->name('results.recap-print');
    Route::get('/rekap-penilaian/export/excel', [ParticipantResultController::class, 'recapExportExcel'])->name('results.recap.export.excel');
    Route::get('/rekap-penilaian/golongan/{category}/pdf', [ParticipantResultController::class, 'recapCategoryPdf'])->name('results.recap.category.pdf');
    Route::get('/rekap-penilaian/juara/penyisihan/pdf', [ParticipantResultController::class, 'recapPenyisihanPdf'])->name('results.recap.winners.penyisihan.pdf');
    Route::get('/rekap-penilaian/juara/final/pdf', [ParticipantResultController::class, 'recapFinalPdf'])->name('results.recap.winners.final.pdf');
    Route::post('/siaran/pengumuman/{announcement}', [BroadcastController::class, 'announcement'])->middleware('role:admin,panitia')->name('broadcast.announcement');
    Route::post('/siaran/jadwal/{schedule}', [BroadcastController::class, 'schedule'])->middleware('role:admin,panitia')->name('broadcast.schedule');
    Route::get('/admin/arsip-peserta', [ParticipantRegistrationController::class, 'trash'])->middleware('role:admin')->name('participants.trash');
    Route::post('/admin/arsip-peserta/impor-arsip-lama', [ParticipantRegistrationController::class, 'importLegacyTrash'])->middleware('role:admin')->name('participants.trash.import-legacy');
    Route::post('/admin/arsip-peserta/{participant}/pulihkan', [ParticipantRegistrationController::class, 'restore'])->middleware('role:admin')->name('participants.restore');
    Route::post('/admin/arsip-peserta/{participant}/hapus-permanen', [ParticipantRegistrationController::class, 'destroyArchived'])->middleware('role:admin')->name('participants.trash.destroy');
    Route::get('/admin/arsip-peserta/{participant}/dokumen/{document}/preview', [ParticipantRegistrationController::class, 'previewTrashedDocument'])->middleware('role:admin')->name('participants.trash.documents.preview');
    Route::get('/admin/arsip-peserta/{participant}/dokumen/{document}', [ParticipantRegistrationController::class, 'downloadTrashedDocument'])->middleware('role:admin')->name('participants.trash.documents.download');
    Route::get('/pendaftaran-peserta', [ParticipantRegistrationController::class, 'index'])->middleware('role:admin,panitia,official,pendamping')->name('participants.index');
    Route::post('/pendaftaran-peserta', [ParticipantRegistrationController::class, 'store'])->middleware('role:admin,panitia,official,pendamping')->name('participants.store');
    Route::get('/data-peserta', [ParticipantRegistrationController::class, 'list'])->middleware('role:admin,panitia,official,pendamping')->name('participants.list');
    Route::get('/data-peserta/export/excel', [ParticipantRegistrationController::class, 'exportExcel'])->middleware('role:admin,panitia,official,pendamping')->name('participants.export.excel');
    Route::get('/data-peserta/export/verifikasi/excel', [ParticipantRegistrationController::class, 'exportVerificationExcel'])->middleware('role:admin,panitia,official,pendamping')->name('participants.export.verification.excel');
    Route::get('/data-peserta/export/pdf', [ParticipantRegistrationController::class, 'exportPdf'])->middleware('role:admin,panitia,official,pendamping')->name('participants.export.pdf');
    Route::get('/data-peserta/export/rekap/pdf', [ParticipantRegistrationController::class, 'exportRecapPdf'])->middleware('role:admin,panitia,official,pendamping')->name('participants.export.recap.pdf');
    Route::get('/data-peserta/export/rekap/excel', [ParticipantRegistrationController::class, 'exportRecapExcel'])->middleware('role:admin,panitia,official,pendamping')->name('participants.export.recap.excel');
    Route::get('/data-peserta/export/golongan/pdf', [ParticipantRegistrationController::class, 'exportByCategoryPdf'])->middleware('role:admin,panitia,official,pendamping')->name('participants.export.by-category.pdf');
    Route::get('/pengambilan/lot', [ParticipantRegistrationController::class, 'lotMenu'])->middleware('role:admin,panitia')->name('participants.lot.menu');
    Route::get('/pengambilan/maqra', [ParticipantRegistrationController::class, 'maqraMenu'])->middleware('role:admin,official,pendamping,panitia')->name('participants.maqra.menu');
    Route::get('/data-peserta/{participant}/nomor-lot', [ParticipantRegistrationController::class, 'lotDraw'])->middleware('role:admin,panitia')->name('participants.lot.draw');
    Route::get('/data-peserta/{participant}/maqra', [ParticipantRegistrationController::class, 'maqraDraw'])->middleware('role:admin,official,pendamping')->name('participants.maqra.draw');
    Route::get('/data-peserta/{participant}/cv', [ParticipantRegistrationController::class, 'downloadCv'])->name('participants.cv');
    Route::post('/data-peserta/{participant}/nomor-lot', [ParticipantRegistrationController::class, 'assignLotNumber'])->middleware('role:admin,panitia')->name('participants.lot.assign');
    Route::post('/data-peserta/{participant}/maqra', [ParticipantRegistrationController::class, 'assignMaqra'])->middleware('role:admin,official,pendamping')->name('participants.maqra.assign');
    Route::post('/data-peserta/{participant}/maqra/reset', [ParticipantRegistrationController::class, 'resetMaqra'])->middleware('role:admin')->name('participants.maqra.reset');
    Route::post('/data-peserta/{participant}/maqra/tukar', [ParticipantRegistrationController::class, 'swapMaqra'])->middleware('role:admin')->name('participants.maqra.swap');
    Route::get('/data-peserta/{participant}/maqra/status', [ParticipantRegistrationController::class, 'maqraStatus'])->middleware('role:admin,official,pendamping')->name('participants.maqra.status');
    Route::post('/data-peserta/{participant}/nomor-lot/reset', [ParticipantRegistrationController::class, 'resetLotNumber'])->middleware('role:admin')->name('participants.lot.reset');
    Route::post('/data-peserta/{participant}/nomor-lot/ubah', [ParticipantRegistrationController::class, 'updateLotNumber'])->middleware('role:admin')->name('participants.lot.update');
    Route::post('/data-peserta/{participant}/nomor-lot/tukar', [ParticipantRegistrationController::class, 'swapLotNumber'])->middleware('role:admin')->name('participants.lot.swap');
    Route::post('/pendaftaran-peserta/surat-mandat', [ParticipantRegistrationController::class, 'uploadMandate'])->middleware('role:official,pendamping')->name('participants.mandate.upload');
    Route::get('/pendaftaran-peserta/surat-mandat/preview', [ParticipantRegistrationController::class, 'previewMandate'])->middleware('role:official,pendamping')->name('participants.mandate.preview');
    Route::get('/pendaftaran-peserta/surat-mandat/{district}/preview', [ParticipantRegistrationController::class, 'previewDistrictMandate'])->middleware('role:admin,panitia')->name('participants.mandate.district-preview');
    Route::post('/pendaftaran-peserta/surat-mandat/{district}/verifikasi', [ParticipantRegistrationController::class, 'verifyMandate'])->middleware('role:admin,panitia')->name('participants.mandate.verify');
    Route::get('/pendaftaran-peserta/{participant}', [ParticipantRegistrationController::class, 'show'])->middleware('role:admin,panitia,official,pendamping')->name('participants.show');
    Route::get('/pendaftaran-peserta/{participant}/edit', [ParticipantRegistrationController::class, 'edit'])->middleware('role:admin,panitia,official,pendamping')->name('participants.edit');
    Route::post('/pendaftaran-peserta/{participant}/edit', [ParticipantRegistrationController::class, 'update'])->middleware('role:admin,panitia,official,pendamping')->name('participants.update');
    Route::post('/pendaftaran-peserta/{participant}/arsipkan', [ParticipantRegistrationController::class, 'archive'])->middleware('role:admin,panitia,official,pendamping')->name('participants.archive');
    Route::get('/pendaftaran-peserta/{participant}/dokumen/{document}/preview', [ParticipantRegistrationController::class, 'previewDocument'])->middleware('role:admin,panitia,official,pendamping')->name('participants.documents.preview');
    Route::get('/pendaftaran-peserta/{participant}/dokumen/{document}', [ParticipantRegistrationController::class, 'downloadDocument'])->middleware('role:admin,panitia,official,pendamping')->name('participants.documents.download');
    Route::post('/pendaftaran-peserta/{participant}/verifikasi', [ParticipantRegistrationController::class, 'verify'])->middleware('role:admin,panitia')->name('participants.verify');
    Route::get('/penilaian', [ScoringController::class, 'index'])->middleware('role:admin,panitia')->name('scoring');
    Route::post('/penilaian/setting', [ScoringController::class, 'storeSettings'])->middleware('role:admin,panitia')->name('scoring.settings.store');
    Route::post('/penilaian/setting/request', [ScoringController::class, 'requestSettingEdit'])->middleware('role:admin,panitia')->name('scoring.settings.request');
    Route::post('/penilaian/setting/buka', [ScoringController::class, 'openSettingEdit'])->middleware('role:admin')->name('scoring.settings.open');
    Route::post('/penilaian', [ScoringController::class, 'store'])->middleware('role:admin,panitia')->name('scoring.store');
    Route::post('/penilaian/request-perbaikan', [ScoringController::class, 'storeCorrectionRequest'])->middleware('role:admin,panitia')->name('scoring.corrections.store');
    Route::get('/penilaian/poll', [ScoringController::class, 'poll'])->middleware('role:admin,panitia')->name('scoring.poll');
    Route::get('/penilaian/mfq', [MfqScoringController::class, 'index'])->middleware('role:admin,panitia')->name('scoring.mfq');
    Route::post('/penilaian/mfq/pilih-regu', [MfqScoringController::class, 'storeSelection'])->middleware('role:admin,panitia')->name('scoring.mfq.selection.store');
    Route::post('/penilaian/mfq/pilih-regu/hapus', [MfqScoringController::class, 'clearSelection'])->middleware('role:admin,panitia')->name('scoring.mfq.selection.clear');
    Route::post('/penilaian/mfq', [MfqScoringController::class, 'store'])->middleware('role:admin,panitia')->name('scoring.mfq.store');
    Route::post('/logout', [AuthController::class, 'destroy'])->name('logout');
    Route::post('/admin/login-sebagai', [AuthController::class, 'impersonate'])->middleware('role:admin')->name('admin.impersonate.store');
    Route::post('/admin/login-sebagai/keluar', [AuthController::class, 'stopImpersonation'])->name('admin.impersonate.stop');
});
