<?php

return [
    'title' => 'Juknis MTQ Kabupaten Tanah Datar XLIII Tahun 2026',
    'host' => 'Kecamatan Pariangan',
    'age_reference_date' => '1 Juli 2026',
    'app' => [
        'name' => 'e-MTQ',
        'homepage_title' => 'e-MTQ Kabupaten Tanah Datar',
        'homepage_tagline' => 'Satu halaman utama untuk mengikuti MTQ dengan lebih mudah.',
        'homepage_description' => 'Pantau jadwal utama, pengumuman terbaru, lokasi lomba, dan cabang yang ditampilkan dalam satu halaman yang rapi.',
    ],
    'footer' => [
        'headline' => 'e-MTQ Kabupaten Tanah Datar',
        'description' => 'Ruang kerja digital ini dihadirkan untuk membantu proses pendaftaran, verifikasi, penilaian, dan pengelolaan data MTQ secara lebih tertata, cepat, dan mudah dipantau oleh semua peran yang terlibat.',
        'contact_label' => 'CP WhatsApp',
        'contact_number' => '0895-0900-7078',
        'attribution_name' => 'Ridho Saputra S.Kom',
        'attribution_role' => 'Pranata Komputer Ahli Pertama - Kantor Kementerian Agama Kab. Tanah Datar',
        'note' => 'Dipakai sebagai sarana pendukung operasional e-MTQ dan komunikasi teknis pengembangan sistem.',
    ],
    'registration_windows' => [
        [
            'label' => 'Masa Pendaftaran Peserta',
            'start_at' => '11 Mei 2026 00:00',
            'end_at' => '18 Mei 2026 23:59',
            'official' => [
                'participant_registration_open' => true,
                'participant_edit_open' => true,
                'participant_verification_open' => false,
                'participant_delete_open' => false,
                'mandate_upload_open' => true,
                'participant_documents_open' => true,
                'participant_lot_open' => false,
            ],
            'panitia' => [
                'participant_registration_open' => false,
                'participant_edit_open' => false,
                'participant_verification_open' => false,
                'participant_delete_open' => false,
                'mandate_upload_open' => false,
                'participant_documents_open' => false,
                'participant_lot_open' => false,
            ],
        ],
        [
            'label' => 'Masa Verifikasi',
            'start_at' => '19 Mei 2026 00:00',
            'end_at' => '25 Mei 2026 23:59',
            'official' => [
                'participant_registration_open' => false,
                'participant_edit_open' => true,
                'participant_verification_open' => true,
                'participant_delete_open' => true,
                'mandate_upload_open' => true,
                'participant_documents_open' => true,
                'participant_lot_open' => false,
            ],
            'panitia' => [
                'participant_registration_open' => false,
                'participant_edit_open' => false,
                'participant_verification_open' => true,
                'participant_delete_open' => false,
                'mandate_upload_open' => false,
                'participant_documents_open' => false,
                'participant_lot_open' => false,
            ],
        ],
    ],
    'registration' => [
        'open' => '11 Mei 2026',
        'close' => '18 Mei 2026',
        'official_edit_start' => '22 Mei 2026',
        'official_edit_end' => '24 Mei 2026',
        'verification_start' => '19 Mei 2026',
        'verification_end' => '25 Mei 2026',
        'announcement' => '26 Mei 2026',
        'objection_start' => '27 Mei 2026',
        'objection_end' => '31 Mei 2026',
    ],
    'event_schedule' => [
        ['date' => '19 Juni 2026', 'time' => '08.00 - 11.30', 'activity' => 'Pendaftaran ulang peserta', 'notes' => 'Jadwal dan lokasi lomba lebih lengkap menyusul.'],
        ['date' => '19 Juni 2026', 'time' => '14.00 - 17.00', 'activity' => 'Pawai pembukaan MTQ', 'notes' => 'Dilanjutkan pembukaan resmi.'],
        ['date' => '19 Juni 2026', 'time' => '20.00 - 24.00', 'activity' => 'Penyisihan cabang tertentu', 'notes' => 'Mulai operasional lomba.'],
        ['date' => '20 Juni 2026', 'time' => '08.00 - 22.00', 'activity' => 'Penyisihan seluruh cabang', 'notes' => 'Sesi penuh.'],
        ['date' => '21 Juni 2026', 'time' => '08.00 - 22.00', 'activity' => 'Penyisihan seluruh cabang', 'notes' => 'Sesi penuh.'],
        ['date' => '22 Juni 2026', 'time' => '08.00 - 13.00', 'activity' => 'Final cabang tertentu', 'notes' => 'Dilanjutkan rapat dewan hakim.'],
        ['date' => '22 Juni 2026', 'time' => '13.00 - 16.00', 'activity' => 'Rapat dewan hakim', 'notes' => 'Finalisasi hasil.'],
        ['date' => '23 Juni 2026', 'time' => '08.00 - 13.00', 'activity' => 'Penutupan MTQ', 'notes' => 'Pengumuman juara dan penutupan.'],
    ],
    'administration_requirements' => [
        'Kartu Keluarga (KK).',
        'KTP elektronik untuk peserta berusia 17 tahun ke atas dan/atau sudah menikah.',
        'Akta kelahiran.',
        'Pas foto berlatar merah.',
    ],
    'participant_rules' => [
        'Peserta adalah peserta terbaik hasil MTQ kecamatan atau hasil seleksi LPTQ kecamatan masing-masing.',
        'Peserta yang pernah menjadi terbaik I sebanyak 2 kali pada cabang dan golongan yang sama tidak diperbolehkan mengikuti cabang/golongan tersebut lagi.',
        'Setiap peserta hanya boleh mengikuti satu golongan musabaqah.',
        'Batas usia maksimal seluruh peserta dihitung mulai tanggal 1 Juli 2026.',
        'Peserta harus berdomisili di Tanah Datar dan dibuktikan dengan Kartu Keluarga.',
        'Setiap kecamatan wajib melampirkan surat mandat peserta utama dan cadangan.',
        'Validasi NIK ke Disdukcapil dianjurkan agar peserta tidak ditolak saat verifikasi.',
    ],
    'performance_rules' => [
        'MFQ dan MSQ adalah cabang beregu yang terdiri dari 3 orang.',
        'Jika satu anggota beregu berhalangan, penampilan masih dapat dilakukan oleh 2 orang.',
        'Jika peserta MFQ atau MSQ tinggal 1 orang maka gugur hak tampil.',
        'Khutbah Jumat dan Adzan terdiri dari 2 orang putra: seorang khatib dan seorang muadzin.',
        'Entri nilai dilakukan oleh operator aplikasi penilaian untuk menjaga keamanan operasional IT.',
    ],
    'competition_system' => [
        'Musabaqah pada umumnya diselenggarakan dalam dua babak: penyisihan dan final.',
        'Seni Kaligrafi Al Qur`an memiliki pola babak khusus sesuai juknis cabang.',
        'Seluruh cabang menentukan juara umum kabupaten.',
    ],
    'objection_rules' => [
        'Official dapat mengajukan protes kepada pengawas dewan hakim paling cepat 5 jam setelah penampilan.',
        'Protes harus dilengkapi bukti otentik.',
        'Jika terbukti terjadi kekeliruan yang merugikan peserta, peserta berhak mengulang penampilan.',
        'Keputusan dewan hakim tidak dapat diganggu gugat setelah mekanisme resmi dijalankan.',
    ],
];
